image: node:16.19

stages:
  - deploy

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y openssh-client

    # create known host file
    - mkdir -p /root/.ssh
    - touch /root/.ssh/known_hosts

    # add ec2 server as known host
    - ssh-keyscan -H ec2-18-157-234-99.eu-central-1.compute.amazonaws.com >> ~/.ssh/known_hosts

    # generate pem file from content of gitlab variable
    - echo "$SSH_PRIVATE_KEY" > my-private-key.pem

    # make new pem file available
    - chmod 400 my-private-key.pem
  script:
    #  ssh to ec2 server and pull from update from git and run db migration 
    - ssh -i my-private-key.pem ubuntu@ec2-18-157-234-99.eu-central-1.compute.amazonaws.com "cd /var/www/html/savingsbox-user-frontend && git pull origin production && npm i && npm run build && pm2 restart UserFrontEnd --update-env && pm2 save"
  only:
    - production